// export {default as userRoutes} from './user.route';
// export {default as bookingRoutes} from './booking.route';
export {default as authRoutes} from './auth/auth.route';
export {default as otpRoutes} from './otp/route';
export {default as roleRoutes} from './role/role.route';
export {default as adminHotelRoutes} from './admin/hotel/adminHotel.route';
export {default as providerHotelRoutes} from './provider/hotel/hotel.route';
export {default as aminitiesRoutes} from './admin/aminities/aminites.route';
export {default as publicPropertyRoutes} from './public/property.route';
export {default as profileRoutes} from './user/profile.route';
export {default as favoriteRoutes} from './user/favorite.route';
export {default as reviewRoutes} from './user/review.route';
export {default as bookingRoutes} from './user/booking.route';
export {default as providerPropertyRoutes} from './provider/property/property.route';
