export * as registerController from './v1/auth/register.controller';
export * as loginController from './v1/auth/login.controller';
export * as refreshTokenController from './v1/auth/refreshToken.controller';
export * as logoutController from './v1/auth/logout.controller';
export * as otpController from './v1/OtpVerification/OtpVerification.controller';
export * as roleController from './v1/role/role.controller';
export * as adminHotelController from './v1/admin/hotel/hotel.controller';
export * as providerHotelController from './v1/provider/hotel/hotel.controller';
export * as aminitiesController from './v1/admin/aminities/amenities.controller';