import dotenv from 'dotenv';
dotenv.config();

export const config = {
    ORIGIN_FRONTEND: process.env.ORIGIN_FRONTEND || '',
    ORIGIN_ADMIN: process.env.ORIGIN_ADMIN || '',
    ORIGIN_FRONTEND_WWW: process.env.ORIGIN_FRONTEND_WWW || '',
    DB_URL: process.env.DB_URL || '',
    SALT: process.env.SALT || '',
    ACCESS_SECRET: process.env.ACCESS_SECRET || '',
    REFRESH_SECRET: process.env.REFRESH_SECRET || '',
    PORT: process.env.PORT || 8000,
    SMTP_HOST: process.env.SMTP_HOST || '',
    SMTP_PORT: process.env.SMTP_PORT || '',
    SMTP_SRC: process.env.SMTP_SRC || '',
    SMTP_MAIL: process.env.SMTP_MAIL || '',
    SMTP_PASSWORD: process.env.SMTP_PASSWORD || '',
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || '',
    PG_DB_URL: process.env.PG_DB_URL || '',
    CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
    CLOUDINARY_APIKEY: process.env.CLOUDINARY_APIKEY,
    CLOUDINARY_APISECRET: process.env.CLOUDINARY_APISECRET,
    RAZORPAY_API_KEY: process.env.RAZORPAY_API_KEY,
    RAZORPAY_API_SECRET: process.env.RAZORPAY_API_SECRET,
    MINIO_ENDPOINT: process.env.MINIO_ENDPOINT,
    MINIO_ACCESS_KEY: process.env.MINIO_ACCESS_KEY,
    MINIO_SECRET_KEY: process.env.MINIO_SECRET_KEY,
    MINIO_BUCKET_NAME: process.env.MINIO_BUCKET_NAME,
    nodeEnv: process.env.NODE_ENV || 'development',
    rateLimitWindowMs:
        Number(process.env.RATE_LIMIT_WINDOW_MS) || 15 * 60 * 1000,
    rateLimitMaxRequests: Number(process.env.RATE_LIMIT_MAX) || 100,
    redisUrl: process.env.REDIS_URL || '',
};
